{
 "title": "Alerts Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Recent Alerts (Table)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{alertstate=\"firing\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}