{
 "title": "HTTP Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  rate(http_request_duration_seconds_bucket[5m])\r\n)\r\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  rate(http_request_duration_seconds_bucket[5m])\r\n)\r\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  rate(http_request_duration_seconds_bucket[5m])\r\n)\r\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Request Rate by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total[5m]))\r\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) * 60\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))\r\n/\r\nsum(rate(http_requests_total[5m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slowest Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  avg by(route)(\r\n    rate(http_request_duration_seconds_sum[5m])\r\n    /\r\n    rate(http_request_duration_seconds_count[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}